### ISSUE TITLE
Project QA feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-rails-regex-format-validations#2]
@chrisvfritz

Change the URL for cloning to include the student's username, not yours.

When I try to `rackup` I get the following error:

> C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/dat                                                                                                                                                 a_source.rb:182:in `rescue in create_default_data_source': No source of timezone                                                                                                                                                  data could be found. (TZInfo::DataSourceNotFound)
> Please refer to http://tzinfo.github.io/datasourcenotfound for help resolving th                                                                                                                                                 is error.

**Comment by KatieMFritz** [comment]
https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Ftzinfo%2Ftzinfo%2Fwiki%2FResolving-TZInfo%3A%3ADataSourceNotFound-Errors%23using-tzinfo-data-with-bundler-or-ruby-on-rails&sa=D&sntz=1&usg=AFQjCNFBPV-fK7HfThq8rklXetgOabTuOg for people on Windows.

**Comment by chrisvfritz** [comment]
Can you try this and see if you get any errors on Windows now?
1. `git clone https://github.com/chrisvfritz/codelab-rails-regex-format-validations.git`
2. `cd codelab-rails-regex-format-validations`
3. `bundle install --without production`
