### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-rails-regex-format-validations#3]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://morning-plateau-6804.herokuapp.com/posts) and meets the following [project](http://lansingcodelab.com/lessons/rails-regex-format-validations/1) criteria:
- [x] In our community, "flurb" is a very, very bad word. If the **title** or **content** contain the word "flurb", or variants such as "Flurb", "flurbing", "flurber", "flerb", "florb", or "fl|_|rb", this error is added to the attribute: `can't include the word "flurb" or a variation thereof`
- [x] Validate that the **name** only contains letters, spaces, periods, dashes, and commas. Otherwise, this error should be added to the name attribute: `isn't a valid name (only letters, spaces, periods, dashes, and commas allowed)`
- [x] To help you know when your regex is working, some tests have been written in [spec/models/post_spec.rb](https://github.com/chrisvfritz/codelab-rails-regex-format-validations/blob/master/spec/models/post_spec.rb). Run `rspec` from your project directory to run these tests. When it reports `0 failures`, you're done!

**Comment by chrisvfritz** [comment]
:+1: :shipit:
